"""Added Event and Booking models.

Revision ID: 79d7fdb057b1
Revises: d0118366c024
Create Date: 2024-06-29 14:11:54.722991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79d7fdb057b1'
down_revision = 'd0118366c024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=120),
               type_=mysql.TIME(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
